name: DHIS2 Deploy Matrix

# Requirements

## Secrets:
## DHIS2_DEBUG_PASSWORD
## DHIS2_PLAY_PASSWORD
env:
    DHIS2_PLAY_PASSWORD: '${{ secrets.DHIS2_PLAY_PASSWORD }}'
    DHIS2_DEBUG_PASSWORD: ${{ secrets.DHIS2_DEBUG_PASSWORD }}
# Controls when the action will run.
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        strategy:
            matrix:
                include: 
                  - baseurl: 'https://debug.dhis2.org/dev'
                    username: 'admin'
                    password-env: 'DHIS2_DEBUG_PASSWORD' # needs to match the environment variable name
                  - baseurl: 'https://play.dhis2.org/dev'
                    username: 'admin'
                    password-env: 'DHIS2_PLAY_PASSWORD'
        runs-on: ubuntu-latest
        steps:
            # include does not support dynamic values, so we need to set the password as an environment variable
            # NOTE: DHIS2_${{matrix.name}}_PASSWORD needs to match env-variables!
            - name: Set password environment variable
              run: echo "D2_PASSWORD=$(echo ${{ matrix.password-env }})" >> $GITHUB_ENV
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  cache: "yarn"

            - name: Install JS dependencies
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn build
            - name: Deploy to DHIS2 instance
              run: yarn run d2-app-scripts deploy ${{ matrix.baseurl }} --username ${{ matrix.username }}
